name: publish

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun lint
      - run: NODE_ENV=production bun build.ts
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun lint
      - run: bun test
      - run: NODE_ENV=production bun build.ts
      - run: |
          echo '@ricsam:registry=https://registry.npmjs.org' >> .npmrc
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
          echo '//registry.npmjs.org/:always-auth=true' >> .npmrc
      - run: bunx --bun changeset publish --access=public --registry=https://registry.npmjs.org/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
